# -*- coding: utf-8 -*-

QUERY_ADMINISTRATOR = 1
LIST_ADMINISTRATOR = 2
EDIT_ADMINISTRATOR = 3 
CREATE_ADMINISTRATOR = 4
DELETE_ADMINISTRATOR = 5       
RESET_OTHER_PASSWORD = 6 
RESET_MY_PASSWORD = 7
MANAGE_PRIVILEGE_GROUP = 8
DELEGATION = 9
HIGH_LEVEL_DELEGATION = 10
DELEGATION_QUERY = 11       
QUERY_USER = 12
QUERY_GROUP_USER = 13
COUNT_USER = 14 
COUNT_GROUP_USER = 15         
MONTHLY_STATISTIC = 16
DAILY_STATISTIC = 17
BUSINESS_STATISTIC = 18
EC_BUSINESS_STATISTIC = 19
SMS_STATISTIC = 20
