# -*- coding: utf-8 -*-

QUERY_ADMINISTRATOR = 1
LIST_ADMINISTRATOR = 2
EDIT_ADMINISTRATOR = 3
CREATE_ADMINISTRATOR = 4
DELETE_ADMINISTRATOR = 5
RESET_OTHER_PASSWORD = 6
RESET_MY_PASSWORD = 7
MANAGE_PRIVILEGE_GROUP = 8
DELEGATION = 9
BUSINESS_HANDLE = 10
BUSINESS_QUERY = 11
QUERY_BUSINESS = 12
CREATE_BUSINESS = 13
LIST_BUSINESS = 14
EDIT_BUSINESS = 15
DELETE_BUSINESS = 16
TERMINAL_QUERY= 17
STATISTIC = 18
WHITELIST = 19
ACTIVITY = 20
APK = 21 
